// @ts-nocheck
import type { BudgetAPIContract, SyncItem } from "./budget-api";
import { now, readStorageRecords, uuid, writeStorageArray } from "../utilities/data-utilities";
import { DateUtils } from "../utilities/date-utilities";
import { monthEnd } from "../utilities/investment-returns";

export type AccountType = "investment" | "debt";
export type AccountActivityType = "contribution" | "payment" | "borrowing";
export interface Account { id:string; name:string; type:AccountType; assignmentId:string; active:boolean; source?:"manual"|"paycheck"; interestRate?:number; lender?:string; createdAt:string; updatedAt:string; }
export interface AccountBalance { id:string; accountId:string; month:string; asOfDate:string; balance:number; notes:string; createdAt:string; createdBy:string; updatedAt:string; updatedBy:string; }
export interface AccountActivity { id:string; accountId:string; date:string; month:string; amount:number; activityType:AccountActivityType; flowType?:"external"|"transfer"; transferId?:string; counterpartyAccountId?:string; createdAt:string; createdBy:string; updatedAt:string; updatedBy:string; }
export interface AccountMonth { accountId:string; month:string; balance:AccountBalance|null; activity:AccountActivity[]; }
export interface AccountMonthInput { accountId:string; month:string; balance:number|string; notes?:string; balanceId?:string; asOfDate?:string; existingActivity?:AccountActivity[]; activity?:Array<Partial<AccountActivity>&Pick<AccountActivity,"amount"|"activityType">>; }
export interface AccountAPIContract { accounts():Account[]; balances():AccountBalance[]; activity():AccountActivity[]; monthData(accountId:string,month:string):AccountMonth|null; load(options?:{refresh?:boolean}):Promise<void>; saveAccount(input:Partial<Account>&Pick<Account,"name"|"type">):Promise<Account>; archiveAccount(id:string):Promise<Account>; saveMonth(input:AccountMonthInput):Promise<AccountMonth|null>; queueImportedMonths(inputs:AccountMonthInput[]):unknown[]; awaitImportedMonths(ids:string[],onProgress?:(progress:{completed:number;total:number})=>void):Promise<string[]>; deleteActivity(id:string):Promise<void>; applyBootstrapData(data:unknown):void; getSyncItems():SyncItem[]; retry(source:string,id:string):void; discard(source:string,id:string):void; }

const KEYS={accounts:"myFinance.accounts.v1",balances:"myFinance.accountBalances.v1",activity:"myFinance.accountActivity.v1",outbox:"myFinance.accountOutbox.v1"};

/** Owns normalized account persistence, offline writes, retries, and month conflict state. */
export function AccountAPI(budget:BudgetAPIContract):AccountAPIContract {
  let loaded=false, syncing:Promise<void>|null=null;
  const read=(key:string)=>readStorageRecords(key) as any[]; const write=(key:string,value:any[])=>writeStorageArray(key,value);
  const offline=()=>typeof navigator!=="undefined"&&navigator.onLine===false;
  const emit=(name:string,detail?:any)=>window.dispatchEvent(new CustomEvent(name,{detail}));
  const request=async(action:string,body:any={})=>{const endpoint=budget.getConfig().endpoint;if(!endpoint)throw new Error("No Apps Script URL is configured.");const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...body}),redirect:"follow"});const payload=await response.json();if(!response.ok||payload?.ok===false)throw new Error(payload?.error||"Account sync failed.");return payload?.data??payload;};
  const accounts=()=>read(KEYS.accounts).sort((a,b)=>a.name.localeCompare(b.name)); const balances=()=>read(KEYS.balances).sort((a,b)=>a.asOfDate.localeCompare(b.asOfDate)); const activity=()=>read(KEYS.activity).sort((a,b)=>a.date.localeCompare(b.date));
  const outbox=()=>read(KEYS.outbox).map(item=>item.status==="syncing"?{...item,status:"pending",nextRetryAt:0}:item);
  const account=(id:string)=>accounts().find(item=>item.id===id)||null;
  const monthData=(accountId:string,month:string)=>account(accountId)?{accountId,month,balance:balances().find(item=>item.accountId===accountId&&item.month===month)||null,activity:activity().filter(item=>item.accountId===accountId&&item.month===month)}:null;
  const dateId=(value:any,fallback="")=>{const text=String(value||"");if(/^\d{4}-\d{2}-\d{2}/.test(text))return DateUtils.toDateId(DateUtils.fromDateId(text.slice(0,10)));const parsed=new Date(text);return Number.isNaN(parsed.getTime())?fallback:DateUtils.toDateId(parsed);};
  const monthId=(value:any,fallback="")=>{const text=String(value||"");if(/^\d{4}-\d{2}$/.test(text))return text;return dateId(text,fallback?`${fallback}-01`:"").slice(0,7);};
  const normalizeBalanceDates=(records:any[])=>records.map((item)=>{const month=monthId(item.month,dateId(item.asOfDate).slice(0,7));return {...item,month,asOfDate:dateId(item.asOfDate,month?monthEnd(month):"")};});
  const normalizeActivityDates=(records:any[])=>records.map((item)=>({
    ...item,
    month:monthId(item.month,dateId(item.date).slice(0,7)),
    date:dateId(item.date,`${monthId(item.month,dateId(item.date).slice(0,7))}-15`),
  }));
  function migrateLegacy(){if(localStorage.getItem(KEYS.accounts)!==null)return;const investments=read("myFinance.investmentAccounts.v1").map(item=>({...item,type:"investment"}));const debts=read("myFinance.debtAccounts.v1").map(item=>({...item,type:"debt"}));const investmentBalances=read("myFinance.investmentBalances.v1");const debtBalances=read("myFinance.debtBalances.v1").map(item=>({...item,accountId:item.accountId||item.debtAccountId}));const contributions=read("myFinance.investmentContributions.v1").map(item=>({...item,activityType:"contribution"}));const payments=read("myFinance.debtPayments.v1").map(item=>({...item,accountId:item.accountId||item.debtAccountId,activityType:item.kind||"payment"}));write(KEYS.accounts,[...investments,...debts]);write(KEYS.balances,[...investmentBalances,...debtBalances]);write(KEYS.activity,[...contributions,...payments]);const investmentOutbox=read("myFinance.investmentMonthOutbox.v1").map(item=>({...item,kind:"month"}));const debtOutbox=read("myFinance.debtOutbox.v1").map(item=>({...item,kind:item.kind==="account"?"account":item.kind==="paymentDelete"?"activityDelete":"month"}));write(KEYS.outbox,[...investmentOutbox,...debtOutbox]);}
  migrateLegacy();
  const applyBootstrapData=(data:any)=>{if(!Array.isArray(data?.accounts))return;const pending=new Set(outbox().flatMap(item=>item.kind==="account"?[item.record?.id]:item.kind==="month"?[item.accountId]:[]));write(KEYS.accounts,[...data.accounts.filter(item=>!pending.has(item.id)),...accounts().filter(item=>pending.has(item.id))]);if(Array.isArray(data.accountBalances))write(KEYS.balances,normalizeBalanceDates(data.accountBalances));if(Array.isArray(data.accountActivity))write(KEYS.activity,normalizeActivityDates(data.accountActivity));loaded=true;emit("budget:accounts-loaded");emit("budget:accounts-changed");};
  const load=async(options:any={})=>{if(loaded&&!options.refresh)return;if(budget.getConfig().endpoint){const data=await request("bootstrap");applyBootstrapData(data);}loaded=true;};
  const enqueue=(operation:any)=>{write(KEYS.outbox,[...outbox().filter(item=>item.id!==operation.id),operation]);emit("budget:sync-changed");void sync();};
  const saveAccount=async(input:any)=>{const existing=input.id?account(input.id):null;const timestamp=now();const record={...existing,...input,id:input.id||uuid(),name:String(input.name||"").trim(),active:input.active!==false,assignmentId:input.assignmentId||budget.SHARED_ASSIGNMENT_ID,source:input.type==="investment"?(input.source||"manual"):"",interestRate:input.type==="debt"?Number(input.interestRate||0):undefined,lender:input.type==="debt"?String(input.lender||""):"",createdAt:existing?.createdAt||timestamp,updatedAt:timestamp};if(!record.name)throw new Error("Enter an account name.");write(KEYS.accounts,[...accounts().filter(item=>item.id!==record.id),record]);enqueue({id:`account:${record.id}`,kind:"account",record,status:"pending",attempts:0,nextRetryAt:0});emit("budget:accounts-changed");return record;};
  const archiveAccount=async(id:string)=>saveAccount({...account(id),id,active:false});
  const saveMonth=async(input:any)=>{const owner=account(input.accountId);if(!owner||owner.active===false)throw new Error("Choose an active account.");const month=monthId(input.month);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw new Error("Choose a reporting month.");const previous=monthData(input.accountId,month);const user=budget.getActiveUser();if(!user)throw new Error("Choose an app user first.");const timestamp=now();const balance={...(previous?.balance||{}),id:previous?.balance?.id||input.balanceId||uuid(),accountId:input.accountId,month,asOfDate:dateId(input.asOfDate,monthEnd(month)),balance:Number(input.balance),notes:String(input.notes||""),createdAt:previous?.balance?.createdAt||timestamp,createdBy:previous?.balance?.createdBy||user.id,updatedAt:timestamp,updatedBy:user.id};const next=(input.activity||[]).map(item=>({...item,id:item.id||uuid(),accountId:input.accountId,month,date:dateId(item.date,`${month}-15`),createdAt:item.createdAt||timestamp,createdBy:item.createdBy||user.id,updatedAt:timestamp,updatedBy:user.id,flowType:item.activityType==="contribution"?(item.flowType||"external"):""}));if(next.some(item=>item.activityType==="contribution"&&owner.type!=="investment")||next.some(item=>item.activityType!=="contribution"&&owner.type!=="debt"))throw new Error("Activity type does not match the account type.");write(KEYS.balances,[...balances().filter(item=>!(item.accountId===input.accountId&&item.month===month)),balance]);write(KEYS.activity,[...activity().filter(item=>!(item.accountId===input.accountId&&item.month===month)),...next]);const prior=outbox().find(item=>item.kind==="month"&&item.accountId===input.accountId&&item.month===month);enqueue({id:prior?.id||uuid(),kind:"month",accountId:input.accountId,month,draft:{accountId:input.accountId,month,balance,activity:next},base:prior?.base||previous,revision:(prior?.revision||0)+1,status:"pending",attempts:0,nextRetryAt:0});emit("budget:accounts-changed");return monthData(input.accountId,month);};
  const deleteActivity=async(id:string)=>{const record=activity().find(item=>item.id===id);if(!record)return;write(KEYS.activity,activity().filter(item=>item.id!==id));enqueue({id:`activity:${id}`,kind:"activityDelete",record,status:"pending",attempts:0,nextRetryAt:0});emit("budget:accounts-changed");};
  async function sync(){if(syncing||offline()||!budget.getConfig().endpoint)return syncing;syncing=(async()=>{for(const item of outbox().filter(item=>item.status==="pending")){try{if(item.kind==="account")await request("saveAccount",{account:item.record});else if(item.kind==="activityDelete")await request("deleteAccountActivity",{id:item.record.id});else{const draft=item.draft;const result=await request("saveAccountMonths",{months:[{id:item.id,accountId:item.accountId,month:item.month,balance:{record:draft.balance,base:item.base?.balance||null},upserts:draft.activity.map(record=>({record,base:(item.base?.activity||[]).find(base=>base.id===record.id)||null})),deletes:(item.base?.activity||[]).filter(base=>!draft.activity.some(record=>record.id===base.id)).map(base=>({id:base.id,base}))}]});const failure=result.failed?.[0];if(failure?.code==="conflict"){write(KEYS.outbox,outbox().map(entry=>entry.id===item.id?{...entry,status:"failed",failureCode:"conflict",current:failure.current,error:failure.error}:entry));continue;}}write(KEYS.outbox,outbox().filter(entry=>entry.id!==item.id));}catch(error){write(KEYS.outbox,outbox().map(entry=>entry.id===item.id?{...entry,status:"pending",attempts:(entry.attempts||0)+1,nextRetryAt:Date.now()+2000,error:error.message}:entry));break;}}})().finally(()=>{syncing=null;emit("budget:sync-changed");});return syncing;}
  const queueImportedMonths=(inputs:any[])=>inputs.map(input=>{void saveMonth(input);return {syncOperationId:outbox().find(item=>item.kind==="month"&&item.accountId===input.accountId&&item.month===input.month)?.id};});
  const awaitImportedMonths=async(ids:string[],progress?:any)=>{await sync();progress?.({completed:ids.length,total:ids.length});return ids;};
  const getSyncItems=()=>outbox().map(item=>({key:item.id,source:item.kind==="month"?"accountMonth":"account",id:item.id,status:item.status,error:item.error,record:item.draft||item.record,current:item.current}));
  const retry=(source:string,id:string)=>{write(KEYS.outbox,outbox().map(item=>item.id===id?{...item,status:"pending",error:"",failureCode:"",nextRetryAt:0}:item));void sync();}; const discard=(source:string,id:string)=>write(KEYS.outbox,outbox().filter(item=>item.id!==id));
  window.addEventListener("online",()=>void sync()); return {accounts,balances,activity,monthData,load,saveAccount,archiveAccount,saveMonth,queueImportedMonths,awaitImportedMonths,deleteActivity,applyBootstrapData,getSyncItems,retry,discard};
}
